name: sjuapp
description: sjuapp
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  postgres: ^2.4.3
  http: ^0.13.3
  google_maps_flutter_ios: ^2.3.2
  google_maps_flutter_web: ^0.5.4+2
  universal_platform: ^1.0.0+1
  intl: ^0.18.1
  flutter_google_places: ^0.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/sjuAppIcon.png"

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_google_places/assets/google_white.png
    - assets/sjuHawk.png
    - assets/thwnd.jpg
    - assets/sjuAppIcon.png